### ISSUE TITLE
Question: does raygui work/build with android?

### ISSUE THREAD

**Issue by Triangle345** [raysan5/raygui#1]
I do not see this anywhere in the docs. Does raygui build/work on android?

**Comment by raysan5** [comment]
Sincerely, I haven't tested it... but it should work ok. When compiling for Android, raylib mouse input functions are directly mapped to touch Tap events, so it should work. The only gui control that could not work is GuiTextBox() because it requires keyboard input.

Right now, another issue is raylib Android template compilation, it seems there is some issue https://github.com/raysan5/raylib/issues/307. I'm working in a custom Android toolchain for raylib, hopefully, it will improve and simplify a lot Android development with raylib.
