### ISSUE TITLE
`GuiDropdownBox()` interaction with `GuiLock()` issues

### ISSUE THREAD

**Issue by btrap** [raysan5/raygui#139]
On line 147  if (dropDown000EditMode || dropDown001EditMode) GuiLock();
This GuiLock logic only works as an accident from line 172's GuiUnlock();
As far as I can tell line 172 is only for locking and unlocking the button examples.
If you remove the button examples the drop down menus lock up all ui when they are opened.

**Comment by raysan5** [comment]
@btrap Just reviewed this mechanism to avoid the dependency on the next `GuiUnlock()`. Still, this locking mechanism is not perfect because of its global nature. `GuiDropdownBox()` would require a separate independent locking mechanism affecting all the other controls in a similar way to the global one... or every control should have it's independent locking mechanism, breaking the immediate-mode style gui.

I'm afraid there is not a proper solution to this issue (or I can't find a proper one considering the library constraints). In any case, current solution should work fine for most situations (self-contained gui panels with several controls not requiring individual locking).
