### ISSUE TITLE
A features I would like to see

### ISSUE THREAD

**Issue by Shadowblitz16** [raysan5/raygui#178]
Can we have the following features please?

- Menubar and nestable menus
- Flag for moving windows with titlebar
- Simple HorizontalLayout and VerticleLayout's

Menu bar would be something like this I guess...
```
Image fileIcon = LoadImage(...);
int menu = int[4]
{
    { "file",  fileIcon, int[3]  
        {
            { "new", null, null },
            null, // seperator
            { "open", null, null },
            { "save", null, null },
            null, // seperator
            { "quit", null, null }
        },
    { "edit", null     , null },
    { "tool", null     , null },
    { "help", null     , null },
}; 
var selection = GuiMenuBar(menu);
if (selection == "save")
{
     // save was pressed.
}
```

Window drag might be like this..
```
Rectangle rect = {0,0,640,480};
Vector2 drag = { 0,0 };
GuiWindow({rect.X+drag.X, rect.Y + drag.Y, rect.Width, rect.Height} "draggable", drag))

```

Layouts might be like this..

```
GuiPushVertical(float space)
GuiPopVertical()
GuiPushHorizontal(float space)
GuiPopHorizontal()
```

These are some pretty basic desktop gui features and they seem like they wouldn't bloat the library too much.
with the layouts and a simple seperator control, Menu could be as simple as..
```Image fileIcon = LoadImage(...);
if(GuiMenu("file", fileIcon))
{
    GuiPushVertical(0);
    GuiMenu("new", null);
    GuiSeperator();
    GuiMenu("load", null);
    if (GuiMenu("save", null))
    {
        // save was pressed.
    }
    GuiSeperator();
    GuiMenu("quit", null);
    GuiPopVertical();
}
GuiMenu("edit", null)
GuiMenu("tool", null)
GuiMenu("help", null)
```

I'm sure the draggable window could be improved as well.

**Comment by raysan5** [comment]
I'm afraid most of this features are out-of-scope for raygui for the moment and it's up to the user to implement them in the user side if desired.

 - Menubar and nestable menus

This is an advance control, it can be implemented using multiple dropdown boxes but considering the imgui nature of the library, a `GuiMenubar()` control could require a big set of input parameters. It can be considered in a future...

 - Flag for moving windows with titlebar

It can be implemented on user side, actually, there is already an usage example: [portable_window](https://github.com/raysan5/raygui/blob/master/examples/portable_window/portable_window.c)

 - Simple HorizontalLayout and VerticleLayout's

Layout system is out-of-scope for raygui. If required, it should be implemented and managed by users or alternatively use another library supporting it by design, like [Dear ImGui](https://github.com/ocornut/imgui).
