### ISSUE TITLE
Error building the examples

### ISSUE THREAD

**Issue by nmsobri** [raysan5/raygui#217]
Hi, i try to compile the examples but got this error:

`ld.exe: i386 architecture of input file ../../raylib/src/raylib.rc.data' is incompatible with i386:x86-64 output`

Can you help me?

**Comment by raysan5** [comment]
@nmsobri This issue is related to the compiler version you are using, `raylib.rc.data` is provided by default for 32bit compilers, you are trying to link it with a 64bit compiler; it needs to be re-compiled for 64bit. Here the isntructions: https://github.com/raysan5/raylib/wiki/Frequently-Asked-Questions#how-do-i-setup-a-custom-icon-for-my-executable
