### ISSUE TITLE
Memory leaks in style functions

### ISSUE THREAD

**Issue by Tinchetsu** [raysan5/raygui#295]
There are memory leaks in the style functions.
This could be a problem if we make a dynamic theme picker or something like that.

The functions have code like this (this is for the dark style, didn't check them all):

    font.recs = (Rectangle *)malloc(font.glyphCount*sizeof(Rectangle));
    memcpy(font.recs, darkFontRecs, font.glyphCount*sizeof(Rectangle));

    font.glyphs = (GlyphInfo *)malloc(font.glyphCount*sizeof(GlyphInfo));
    memcpy(font.glyphs, darkFontChars, font.glyphCount*sizeof(GlyphInfo));

The problem with that, is that the allocated memory can never be freed.
Possible solution could be it just assign the values, since they are not used outside of this function(?)

This is the change that I did to the dark style:

    font.recs = darkFontRecs; 
    font.glyphs = darkFontChars;

**Comment by Tinchetsu** [comment]
As I was playing with this, I found out that I could get the font with GuiGetFont(), and manually free all these pointers, a bit ugly, but with that I can avoid the leaks.
Maybe we can have an _GuiUnloadStyleXXX_ for this?

**Comment by raysan5** [comment]
@Tinchetsu Wow! Thanks for reporting! I don't know how I missed it!

Direct assignation could be a solution in the case styles are provided from a code file (.h) but in then that data can not be loaded because it belongs to const data memory segment.

Probably providing a `GuiUnloadStyle()` function is the best approach... actually, only the `Font` requires that unloading because the rest of the style data directly uses the global state of raygui... actually, `Font` should be something like `GuiFont`, to be independent of raylib...

Anyway, I'll look for a solution to this issue as soon as possible.

**Comment by raysan5** [comment]
@Tinchetsu One possible _temporal_ solution with current implementation is just calling `UnloadFont(GuiGetFont());` before loading any new style. Far from perfect but considering `Font` should/could be managed externally by the user, it makes sense.

Probably the best approach is providing some abstraction layer for `GuiFont` over raylib `Font` but it will increase the complexity of the code...

**Comment by Tinchetsu** [comment]
Thanks, I can go with that, not a problem.
Thank you @raysan5 for your great work with raylib and all the derivative stuff. Love it.

**Comment by raysan5** [comment]
@funlw65 Wow! That application UI looks really beautiful! Congratulations!

**Comment by raysan5** [comment]
Reviewed with a previous solution that I don't know why I removed. 

Now, before loading any new style, `GuiLoadStyleDefault()` should be called, it frees any previous font `texture`, `recs` and `glyphs`.

So, the `style.h` generated should keep allocating memory for `recs` and `glyphs` instead of assigning directly the global data.
