### ISSUE TITLE
Provide `GuiFloatValueBox()`

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raygui#343]
Sometimes people need to be able to view and edit float values

**Comment by raysan5** [comment]
Yeah, I agree but that's actually a quite complex function, the "dot" possition depends on the locale of the system and could be difficult to manage properly.

**Comment by benjibst** [comment]
I tried to make this today because i needed it myself, but i got stuck because when editing the float value's decimal places (pressing backspace), on the next function call they are printed out again. I think this needs some external text memory where you first edit the text and then update the value. @raysan5 pls let me know what you think, im trying to help but idk if this is the right approach

**Comment by raysan5** [comment]
@benjibst Afaik, approach should be similar to `GuiValueBox()` but parsing the value as a `float` (instead of `int`) and probably limiting it to 3 decimal positions.

**Comment by benjibst** [comment]
@danielchasehooper I made this now, on my profile you can find a fork to raylib and raygui if you still need it. the usage is a bit different, you have to provide a data buffer when you call the function where it stores the string representation of the float.

**Comment by benjibst** [comment]
@raysan5 i made a pull request for this, would you mind taking a look?

**Comment by raysan5** [comment]
Related PR https://github.com/raysan5/raygui/pull/356. We can continue the discussion in there.
