### ISSUE TITLE
int GuiGrid(...)  - return value never modified

### ISSUE THREAD

**Issue by n67094** [raysan5/raygui#359]
Hi,

Here the result var have no purpose right ? What was the intention ? 

https://github.com/raysan5/raygui/blob/2c8dc854d4e585761c2d4c77b4abbc46d298d5be/src/raygui.h#L3887

**Comment by raysan5** [comment]
@n67094 Since `raygui 4.0` all controls funtions return an integer value, reserved for some kind of internal state return when needed, several controls use them but not all. This part still requires some work to determine the possible return values common to all controls (i.e mouse hover control, mouse down, control focused...) or specific control internal state values... It's a work-in-progress.
