### ISSUE TITLE
Font error in RGS File

### ISSUE THREAD

**Issue by anatagawa** [raysan5/raygui#66]
I'm trying to use Jungle RGS Style , and have an error for the font

`WARNING: [(null)/"Pixel.otf"] TTF file could not be opened`

the problem is the `(null)`

[Debug Raygui.zip](https://github.com/raysan5/raygui/files/4082860/Debug.Raygui.zip)

**Comment by raysan5** [comment]
@anatagawa solved. This issue was a bit tricky, actually there were two different issues here:

 - [x] raylib: `GetDirectoryPath()` returned `NULL` in case of no directory path, now it returns current directory `./`. Addressed in commit https://github.com/raysan5/raylib/commit/46774a8167b061c5f438ed4ddf607669d9e9f322
 - [x] raygui: Default style is loaded lazily, that way we avoid user manual initialization, but when we call `GuiLoadStyle()` -> `GuiSetFont()` -> `GuiSetStyle()` -> `if (!guiStyleLoaded) GuiLoadStyleDefault();` and loaded font was overwriten!

Now it should work ok.
